version: '3.8'

services:
  manim-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - VIDEOS_DIR=/app/videos
      - TEMP_DIR=/tmp/manim_videos
      - LOG_LEVEL=INFO
      - MAX_CONCURRENT_VIDEOS=3
      - VIDEO_RETENTION_DAYS=7
    volumes:
      - ./generated_videos:/app/videos
      - /tmp/manim_videos:/tmp/manim_videos
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3